sudo: required

language: generic


services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t student/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true student/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success !!"

before_deploy:
  - zip -r docker-react-app .
  - mkdir -p deploy
  - mv docker-react-app.zip deploy/docker-react-app.zip

# deploy 내에 / 사용 안됨.
deploy:
  - provider: s3
    bucket: docker-bucket-test # s3 버킷
    region: ap-northeast-2
    local_dir: deploy
    skip_cleanup: true
    wait_until_deployed : true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: docker-bucket-test # s3 버킷
    key: docker-react-app.zip  # S3 버킷에 저장된 docker-react-app.zip 파일을 EC2로 배포
    bundle_type: zip
    application: Lightsail-codedeploy-app # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: Lightsail-codedeploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed : true
    on:
      branch: master

notifications:
  email:
    recipients:
      - hn12344@naver.com
 
 