version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/deploy/docker-react-app-mac/  # S3에서 가지고온 파일을 저장할 디렉터리 지정

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart: # 배포가 끝나면 아래 명령어를 실행
    - location: deploy.sh
      timeout: 180 
      runas: ec2-user